### ISSUE TITLE
getElement returns non-nullable HTMLElement

### ISSUE THREAD

**Issue by flut1** [mediamonks/muban-core#2]
The `getElement` method returns the result of a `querySelector` call, and for that reason should be marked as  nullable (or it should throw an error in case of no results).

**Comment by flut1** [comment]
This is fixed with #1 . Do we still intent to merge this?

**Comment by skulptur** [comment]
I think we should throw an error that makes it obvious what element was not found and where, instead of adding null to the types. If we add null, while technically correct, it might generate bad practices in the code like using the ! operator to remove null from the type or just casting. Throwing is also more backwards compatible with current projects.

**Comment by ThaNarie** [comment]
There are 2 scenarios to be taken into account:
1) The developer expects an element to always be there, since it's always in the template/html
2) The developer knows something is optional (since the element is rendered in a condition), and will check on it.

The two approaches interact with the two scenarios differently
- a) when not throwing, you expect the developer to do a check. This is something that's already been done for 2) (optional elements), and should ideally be done everything else as well.
Using the `!` type operator is not a good idea in these cases (unless you're in a code block that can only execute once the element is there, like a click handler)
- b) when throwing, we can make 1) more clear (showing a better custom error message), but this won't work for option 2), unless we wrap a try-catch around it, which makes it kind of cumbersome to use.

I think we first need to answer this question; what is the expected behaviour if an element is missing that is expected to be present.
- Should the whole page crash? (that's basically the current behaviour for any code in the constructor)
- Should the component itself not render? (would need some custom handling)
- Should it ignore just that element, and work partly? (would be the logical result of null-checking, but can have the same effect with try-catch)

Since `getElement` is mainly a type-wrapper around `querySelector`, and we can deal with optional elements, I'm more leaning towards including `null` in the return type to force proper null-checking.

We could also go another route by adding a flag to mark the method as expecting something, but that would be annoying with 2 optional parameters.

Let me know if you still feel the same, and also curious what others think.

**Comment by skulptur** [comment]
I agree with adding null type being that it is just a wrapper after all. How can I help get this done? Separate PR since the one that is open has merge conflicts?
